name: rewardrangerapp
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  dio: ^5.4.3+1
  logger: ^2.3.0
  awesome_snackbar_content: ^0.1.3
  awesome_snackbar_content_new: ^0.1.2
  get_it: ^7.6.7
  flutter_secure_storage: ^9.2.2
  google_mobile_ads: ^5.1.0
  device_info_plus: ^10.1.0
  flutter_jailbreak_detection: ^1.10.0
  audioplayers: ^6.0.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  lottie: ^3.1.2
  loading_animation_widget: ^1.2.1
  syncfusion_flutter_datepicker: ^26.1.40
  flutter_zoom_drawer: ^3.2.0
  country_code_picker: ^3.0.0
  intl_phone_number_input: ^0.7.4
  intl: ^0.19.0
  country_picker: ^2.0.26
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/boom_audio.mp3
    - assets/animation/reward_animation.json

  fonts:
    - family: LucidaSans
      fonts:
        - asset: assets/font/LSANS.TTF
          weight: 400
        - asset: assets/font/LTYPEBO.TTF
          weight: 700
